### ISSUE TITLE
ypeError: User.comparePassword is not a function

### ISSUE THREAD

**Issue by mirazzaq** [marley-nodejs/Build-a-Real-Time-web-app-in-node.js-Angular.js-mongoDB#2]
`Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
events.js:141
      throw er; // Unhandled 'error' event
      ^

TypeError: User.comparePassword is not a function
    at /Users/Irfan/Documents/NodePractice/userStory/app/routes/api.js:65:30
    at /Users/Irfan/Documents/NodePractice/userStory/node_modules/mongoose/lib/query.js:2546:18
    at newTickHandler (/Users/Irfan/Documents/NodePractice/userStory/node_modules/mongoose/node_modules/mpromise/lib/promise.js:234:18)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)`

**Comment by webmakaka** [comment]
Hi, look on the attached picture!

![mirazzaq](https://cloud.githubusercontent.com/assets/10372159/22856387/774bf73e-f0a1-11e6-8d4b-19dc143a02a3.png)
